### ISSUE TITLE
Add groupings to MultiSelect component

### ISSUE THREAD

**Issue by mnicole** [gumgum/gumdrops#27]
We need to add the ability to group options into subgroups in a multi select.

This will operate a bit differently from the current implementation here: http://ds.gumgum.com/stable/#gds-multi-select, but it can use the same structure and classes.

We would like the subcategory options to be default opened at all times, so when you open the multi select, you see all options and all subcategory options. A check on a parent category should default check all of the options in a subcategory. And unchecking a parent should default uncheck all of the sub options. You should still be able to check or uncheck a subcategory on its own without the parent, although if someone checks all of the subcategories, it makes sense to also have the parent checked.

For now, let's just handle one level of parent -> children.

**Comment by jscottsmith** [comment]
released [1.5.0](https://github.com/gumgum/gumdrops/tree/1.5.0)
