### ISSUE TITLE
Create Table component

### ISSUE THREAD

**Issue by mnicole** [gumgum/gumdrops#4]
http://ds.gumgum.com/stable/#gds-table

**Comment by jscottsmith** [comment]
I'll take this one, since we can use it on PM. 😬

**Comment by mnicole** [comment]
yessssss we need it really badly :)

bonus points if it can do sorting!

**Comment by jscottsmith** [comment]
*more grimacing*

**Comment by mnicole** [comment]
_grimacing intensifies_

**Comment by edrpls** [comment]
![grimace](https://user-images.githubusercontent.com/1082158/38965938-32a87bb4-4345-11e8-9420-a52f1737bf35.jpg)

**Comment by jscottsmith** [comment]
landed in [v1.3.0](https://github.com/gumgum/gumdrops/tree/v1.3.0)
