### ISSUE TITLE
Add "responsive" option to <Tables>

### ISSUE THREAD

**Issue by jscottsmith** [gumgum/gumdrops#45]
Should add an option for `isResponsive` that ads a wrapper around the table with `gds-table--responsive` class that allows the table to horizontally scroll. 

```
<div className="gds-table--responsive">
    <table className="gds-table>
        ...
    </table>
</div>
```

**Comment by rmcp1g15** [comment]
I can take on this issue if thats ok

**Comment by jscottsmith** [comment]
@rmcp1g15 of course, thanks.

**Comment by mnicole** [comment]
done in https://github.com/gumgum/gumdrops/pull/47
