### ISSUE TITLE
SearchMultiselect - sm size should use small tags

### ISSUE THREAD

**Issue by mnicole** [gumgum/gumdrops#5]
The SearchMultiSelect tag list should also use small tags. See - http://ds.gumgum.com/stable/#gds-search-select

**Comment by garrettbear** [comment]
Based on the design system, xs & sm SearchMultiSelect should be using an x-small tag. Anything greater (md, lg, xl) should be using a small tag. Even though we currently don't have this gumdrop component to support lg or xl.

**Comment by mnicole** [comment]
lg and xl 😱

**Comment by mnicole** [comment]
fixed in 1.8.0
