### ISSUE TITLE
Switch to using classnames on all components

### ISSUE THREAD

**Issue by mnicole** [gumgum/gumdrops#7]
We are concatenating the classes in most of the components, but we recently introduced the "classnames" package (documentation here - https://github.com/JedWatson/classnames). This issue is to convert the rest of our components to using it. You can find an example of its usage here: https://github.com/gumgum/gumdrops/blob/master/components/atoms/AccordionItem.jsx

1. Check all of the components and if they are not currently using classnames (cx), change logic to use classnames.
2. Remove trimString helper function.
3. Check to see if your components render properly and are not adding a class 'undefined' when the component is used.

**Comment by jscottsmith** [comment]
Should be refactored to use `classnames` too which will probably fix the bug in the process.

**Comment by mnicole** [comment]
Yeah actually i just noticed this on some other components too, so I'm going to change this to "use classnames on all components"
